/** Declaration file generated by dts-gen */

export = swagger_extra;

declare class swagger_extra {
    /**
     * @param configDirPath swagger接口文档xx.yaml所在文件夹
     * @param controllerDirPath 接口文件xx.js将写入的文件夹
     * @param isSwaggerOpen 是否生成swagger相关路由
     * @param isAutoFixControllersOpen 是否将接口自动写入接口文件xx.js
     */
    constructor(configDirPath: any, controllerDirPath: any, isSwaggerOpen: any, isAutoFixControllersOpen: any);

    getRoutes(): any;

}

