/** Declaration file generated by dts-gen */

export = swagger_extra;

declare class swagger_extra {
    /**
     * @param configDirPath swagger接口文档xx.yaml所在文件夹
     * @param controllerDirPath 接口文件xx.js将写入的文件夹
     * @param options 其他设置
     */
    constructor(configDirPath: any, controllerDirPath: any, options: {
        //是否生成swagger相关路由，默认为是
        isSwaggerOpen?: boolean = true,
        //是否将接口自动写入接口文件xx.js，默认为是
        isAutoFixControllersOpen?: boolean = true
        //获取post参数对象的代码，默认为：ctx.request.body
        postBodyGetCode?: string = 'ctx.request.body',
        //获取get参数对象的代码，默认为：ctx.param
        getParamsGetCode?: string = 'ctx.params',
        //返回数据格式，示例：ctx.body = {code: 200, 'message': 'success', data: {}}
        controllerReturnCode?: string = "ctx.body = {code: 200, 'message': 'success', data: {}};",
    });

    getRoutes(): any;

}

